In [1]:
import numpy
numpy.__version__

'1.12.0'

In [2]:
import numpy as np

In [3]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [4]:
np.array([1,2,3,4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [5]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [8]:
np.full((3,5),3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [12]:
np.random.random((3,3))

array([[ 0.8392307 ,  0.24269147,  0.29449775],
       [ 0.01689823,  0.43337393,  0.80009723],
       [ 0.35636852,  0.96457353,  0.53706908]])

In [13]:
np.random.normal(0, 1, (3,3))

array([[-0.45867136,  1.30696404,  1.51342166],
       [ 2.23764407, -0.9606498 ,  1.21525151],
       [ 0.2769522 , -0.52241173,  0.58257052]])

In [14]:
np.random.randint(0, 10, (3,3))

array([[3, 3, 7],
       [9, 1, 1],
       [6, 0, 9]])

In [15]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [16]:
np.empty(3)

array([ 1.,  1.,  1.])